<?php

use Illuminate\Database\Seeder;

class PermitTableSeeder extends Illuminate\Database\Seeder {
	
	public function run(){
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>1,
			'option_id'=>1			
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>1,
			'option_id'=>2			
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>1,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>1,
			'option_id'=>4
			)
		);\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>1,
			'option_id'=>5			
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>1,
			'option_id'=>6			
			)
		);		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>2,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>2,
			'option_id'=>2
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>2,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>2,
			'option_id'=>4
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>2,
			'option_id'=>5
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>2,
			'option_id'=>6
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>3,
			'option_id'=>1
			)
		);		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>3,
			'option_id'=>2
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>3,
			'option_id'=>3
			)
		);		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>3,
			'option_id'=>4
			)
		);		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>3,
			'option_id'=>5
			)
		);		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>3,
			'option_id'=>6
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>4,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>4,
			'option_id'=>2
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>4,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>4,
			'option_id'=>4
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>4,
			'option_id'=>5
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>4,
			'option_id'=>10
			)
		);		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>5,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>5,
			'option_id'=>2
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>5,
			'option_id'=>4
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>5,
			'option_id'=>5
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>5,
			'option_id'=>6
			)
		);
		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>6,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>6,
			'option_id'=>2
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>6,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>6,
			'option_id'=>4
			)
		);
		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>6,
			'option_id'=>6
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>6,
			'option_id'=>7
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>6,
			'option_id'=>8
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>6,
			'option_id'=>9
			)
		);		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>7,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>7,
			'option_id'=>4
			)
		);		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>7,
			'option_id'=>6
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>7,
			'option_id'=>12
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>7,
			'option_id'=>13
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>7,
			'option_id'=>14
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>7,
			'option_id'=>18
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>7,
			'option_id'=>19
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>7,
			'option_id'=>20
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>7,
			'option_id'=>21
			)
		);
		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>8,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>8,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>8,
			'option_id'=>6
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>9,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>9,
			'option_id'=>4
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>9,
			'option_id'=>6
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>9,
			'option_id'=>15
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>9,
			'option_id'=>16
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>9,
			'option_id'=>17
			)
		);	
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>10,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>10,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>10,
			'option_id'=>6
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>10,
			'option_id'=>4
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>11,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>11,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>11,
			'option_id'=>4
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>11,
			'option_id'=>6
			)
		);
		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>12,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>12,
			'option_id'=>3
			)
		);
		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>13,
			'option_id'=>22
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>13,
			'option_id'=>23
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>14,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>14,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>15,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>1,
			'module_id'=>15,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>6,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>6,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>6,
			'option_id'=>4
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>6,
			'option_id'=>6
			)
		);		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>6,
			'option_id'=>7
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>6,
			'option_id'=>8
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>6,
			'option_id'=>9
			)
		);
		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>7,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>7,
			'option_id'=>4
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>7,
			'option_id'=>6
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>7,
			'option_id'=>12
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>7,
			'option_id'=>13
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>7,
			'option_id'=>14
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>7,
			'option_id'=>18
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>7,
			'option_id'=>19
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>7,
			'option_id'=>20
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>8,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>8,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>8,
			'option_id'=>6
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>9,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>9,
			'option_id'=>4
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>9,
			'option_id'=>6
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>9,
			'option_id'=>15
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>9,
			'option_id'=>16
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>9,
			'option_id'=>17
			)
		);		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>10,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>10,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>10,
			'option_id'=>4
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>10,
			'option_id'=>6
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>11,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>11,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>11,
			'option_id'=>4
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>11,
			'option_id'=>6
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>12,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>12,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>13,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>13,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>14,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>14,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>15,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>15,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>3,
			'module_id'=>7,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>3,
			'module_id'=>8,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>3,
			'module_id'=>8,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>4,
			'module_id'=>7,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>4,
			'module_id'=>7,
			'option_id'=>4
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>4,
			'module_id'=>7,
			'option_id'=>13
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>4,
			'module_id'=>7,
			'option_id'=>14
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>4,
			'module_id'=>8,
			'option_id'=>3
			)
		);
		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>6,
			'module_id'=>7,
			'option_id'=>3
			)
		);	
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>6,
			'module_id'=>7,
			'option_id'=>12
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>6,
			'module_id'=>7,
			'option_id'=>13
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>6,
			'module_id'=>7,
			'option_id'=>14
			)
		);	
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>6,
			'module_id'=>8,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>2,
			'module_id'=>8,
			'option_id'=>4
			)
		);
		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>6,
			'module_id'=>9,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>6,
			'module_id'=>9,
			'option_id'=>15
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>6,
			'module_id'=>9,
			'option_id'=>16
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>6,
			'module_id'=>9,
			'option_id'=>17
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>6,
			'module_id'=>10,
			'option_id'=>3
			)
		);
		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>6,
			'module_id'=>11,
			'option_id'=>3
			)
		);
		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>6,
			'module_id'=>12,
			'option_id'=>3
			)
		);
		
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>6,
			'module_id'=>13,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>6,
			'module_id'=>14,
			'option_id'=>1
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>6,
			'module_id'=>14,
			'option_id'=>3
			)
		);

		\DB::table('seg_permit')->insert(array(
			'rol_id'=>9,
			'module_id'=>7,
			'option_id'=>3
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>9,
			'module_id'=>7,
			'option_id'=>4
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>9,
			'module_id'=>7,
			'option_id'=>13
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>9,
			'module_id'=>7,
			'option_id'=>14
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>9,
			'module_id'=>7,
			'option_id'=>21
			)
		);
		\DB::table('seg_permit')->insert(array(
			'rol_id'=>9,
			'module_id'=>8,
			'option_id'=>3
			)
		);
		
		
		
		
						
	}
	
}
