<?php

use Illuminate\Database\Seeder;

class UserTableSeeder extends Illuminate\Database\Seeder {
	
	public function run(){
		\DB::table('seg_user')->insert(array(
			'name'=>'superadmin',
			'email'=>'super@yopmail.com',
			'password'=>\Hash::make('0000'),
			'active'=>1,
			'login'=>0,
			'ip'=>'0',
			'rol_id'=>1
			)
		);
		\DB::table('seg_user')->insert(array(
			'name'=>'admin',
			'email'=>'admin@yopmail.com',
			'password'=>\Hash::make('0000'),
			'active'=>1,
			'login'=>0,
			'ip'=>'0',
			'rol_id'=>2
			)
		);
		\DB::table('seg_user')->insert(array(
			'name'=>'asesor',
			'email'=>'asesor@yopmail.com',
			'password'=>\Hash::make('0000'),
			'active'=>1,
			'login'=>0,
			'ip'=>'0',
			'rol_id'=>4
			)
		);
		\DB::table('seg_user')->insert(array(
			'name'=>'asesor2',
			'email'=>'asesor1@yopmail.com',
			'password'=>\Hash::make('0000'),
			'active'=>1,
			'login'=>0,
			'ip'=>'0',
			'rol_id'=>9
		)
		);
		\DB::table('seg_user')->insert(array(
			'name'=>'amigo',
			'email'=>'amigo@yopmail.com',
			'password'=>\Hash::make('0000'),
			'active'=>1,
			'login'=>0,
			'ip'=>'0',
			'rol_id'=>3
			)
		);
		\DB::table('seg_user')->insert(array(
			'name'=>'amigo2',
			'email'=>'amigo2@yopmail.com',
			'password'=>\Hash::make('0000'),
			'active'=>1,
			'login'=>0,
			'ip'=>'0',
			'rol_id'=>3
			)
		);
		\DB::table('seg_user')->insert(array(
			'name'=>'amigo3',
			'email'=>'amigo3@yopmail.com',
			'password'=>\Hash::make('0000'),
			'active'=>1,
			'login'=>0,
			'ip'=>'0',
			'rol_id'=>3
			)
		);
		\DB::table('seg_user')->insert(array(
			'name'=>'asesorf',
			'email'=>'asesorfinanciero@yopmail.com',
			'password'=>\Hash::make('0000'),
			'active'=>1,
			'login'=>0,
			'ip'=>'0',
			'rol_id'=>6
		)
		);
	}
}
