<?php

use Illuminate\Database\Seeder;

class UserProfileTableSeeder extends Illuminate\Database\Seeder {
	
	public function run(){
		\DB::table('seg_user_profile')->insert(array(
			'identificacion'=>100000001,
			'type_id'=>'Cedula Ciudadania',
			'names'=>'Super',
			'surnames'=>'Administrator',
			'birthdate'=>'1988/05/25',
			'birthplace'=>'Medellín',
			'sex'=>'Masculino',
			'adress'=>'Cr 1 #1-1',
			'home'=>'Propia',
			'state'=>'Antioquia',
			'city'=>'Envigado',
			'neighborhood'=>'Almendros',
			'avatar'=>'default.png',
			'description'=>'default',
			'template'=>'default',
			'movil_number'=>5555555555,
			'fix_number'=>5555555,			
			'user_id'=>1	
			)
		);
		\DB::table('seg_user_profile')->insert(array(
			'identificacion'=>100000002,
			'type_id'=>'Cedula Ciudadania',
			'names'=>'Administrador',
			'surnames'=>'ClubAmigos',
			'birthdate'=>'1988/05/25',
			'birthplace'=>'Medellín',
			'sex'=>'Masculino',
			'adress'=>'Cr 1 #1-1',
			'state'=>'Antioquia',
			'home'=>'Propia',
			'city'=>'Envigado',
			'neighborhood'=>'Almendros',
			'avatar'=>'default.png',
			'description'=>'default',
			'template'=>'default',
			'movil_number'=>5555555555,
			'fix_number'=>5555555,
			'date_start'=>'2005/05/25',
			'code_adviser'=>10000,
			'date_in'=>'2005/08/02',
			'salary' => 140000,
			'reference' => 'Jaun Gabriel',
			'reference_adress' => 'Cr50 #45-54',
			'reference_phone' => 3214567,
			'user_id'=>2			
			)
		);
		\DB::table('seg_user_profile')->insert(array(
			'identificacion'=>100000003,
			'type_id'=>'Cedula Ciudadania',
			'names'=>'Asesor',
			'surnames'=>'ClubAmigos',
			'birthdate'=>'1988/05/25',
			'birthplace'=>'Medellín',
			'sex'=>'Masculino',
			'adress'=>'Cr 1 #1-1',
			'state'=>'Antioquia',
			'home'=>'Propia',
			'city'=>'Envigado',
			'neighborhood'=>'Almendros',
			'avatar'=>'default.png',
			'description'=>'default',
			'template'=>'default',
			'movil_number'=>5555555555,
			'fix_number'=>5555555,
			'date_start'=>'2005/05/25',			
			'code_adviser'=>10001,
			'date_in'=>'2005/08/02',
			'salary' => 140000,
			'reference' => 'Jaun Gabriel',
			'reference_adress' => 'Cr50 #45-54',
			'reference_phone' => 3214567,
			'user_id'=>3			
			)
		);		
		\DB::table('seg_user_profile')->insert(array(
			'identificacion'=>100000005,
			'type_id'=>'Cedula Ciudadania',
			'names'=>'Asesor2',
			'surnames'=>'Clubamigos',
			'birthdate'=>'1988/05/25',
			'birthplace'=>'Medellín',
			'sex'=>'Masculino',
			'adress'=>'Cr 1 #1-1',
			'home'=>'Propia',
			'state'=>'Antioquia',
			'city'=>'Envigado',
			'neighborhood'=>'Almendros',
			'avatar'=>'default.png',
			'description'=>'default',
			'template'=>'default',
			'movil_number'=>5555555555,
			'fix_number'=>5555555,
			'date_start'=>'2005/05/25',
			'code_adviser'=>10002,
			'date_in'=>'2005/08/02',
			'salary' => 140000,
			'reference' => 'Jaun Gabriel',
			'reference_adress' => 'Cr50 #45-54',
			'reference_phone' => 3214567,
			'user_id'=>4
			)
		);
		\DB::table('seg_user_profile')->insert(array(
			'identificacion'=>100000004,
			'type_id'=>'Cedula Ciudadania',
			'names'=>'Amigo',
			'surnames'=>'Clubamigos',
			'birthdate'=>'1988/05/25',
			'birthplace'=>'Medellín',
			'sex'=>'Masculino',
			'adress'=>'Cr 1 #1-1',
			'home'=>'Propia',
			'state'=>'Antioquia',
			'city'=>'Envigado',
			'neighborhood'=>'Almendros',
			'avatar'=>'default.png',
			'description'=>'default',
			'template'=>'default',
			'movil_number'=>5555555555,
			'fix_number'=>5555555,			
			'profession'=>'Amigo',
			'paymentadress'=>'Cr 2 #2-2',
			'reference'=>'Pedra',
			'reference_phone'=>'999-99-99',
			'location'=>57,
			'user_id'=>5
			)
		);
		\DB::table('seg_user_profile')->insert(array(
			'identificacion'=>100000006,
			'type_id'=>'Cedula Ciudadania',
			'names'=>'Amigo2',
			'surnames'=>'Clubamigos',
			'birthdate'=>'1988/05/25',
			'birthplace'=>'Medellín',
			'sex'=>'Masculino',
			'adress'=>'Cr 1 #1-1',
			'home'=>'Propia',
			'state'=>'Antioquia',
			'city'=>'Bello',
			'neighborhood'=>'Almendros',
			'avatar'=>'default.png',
			'description'=>'default',
			'template'=>'default',
			'movil_number'=>5555555555,
			'fix_number'=>5555555,			
			'profession'=>'Amigo',
			'paymentadress'=>'Cr 2 #2-2',
			'reference'=>'Pedra',
			'reference_phone'=>'999-99-99',
			'location'=>57,
			'user_id'=>6
			)
		);
		\DB::table('seg_user_profile')->insert(array(
			'identificacion'=>100000007,
			'type_id'=>'Cedula Ciudadania',
			'names'=>'Amigo3',
			'surnames'=>'Clubamigos',
			'birthdate'=>'1988/05/25',
			'birthplace'=>'Medellín',
			'sex'=>'Masculino',
			'adress'=>'Cr 1 #1-1',
			'home'=>'Propia',
			'state'=>'Antioquia',
			'city'=>'Envigado',
			'neighborhood'=>'Almendros',
			'avatar'=>'default.png',
			'description'=>'default',
			'template'=>'default',
			'movil_number'=>5555555555,
			'fix_number'=>5555555,			
			'profession'=>'Amigo',
			'paymentadress'=>'Cr 2 #2-2',
			'reference'=>'Pedra',
			'reference_phone'=>'999-99-99',
			'location'=>57,
			'user_id'=>7
			)
		);
		\DB::table('seg_user_profile')->insert(array(
			'identificacion'=>100000008,
			'type_id'=>'Cedula Ciudadania',
			'names'=>'Asesor Financiero',
			'surnames'=>'Clubamigos',
			'birthdate'=>'1988/05/25',
			'birthplace'=>'Medellín',
			'sex'=>'Masculino',
			'adress'=>'Cr 1 #1-1',
			'home'=>'Propia',
			'state'=>'Antioquia',
			'city'=>'Envigado',
			'neighborhood'=>'Almendros',
			'avatar'=>'default.png',
			'description'=>'default',
			'template'=>'default',
			'movil_number'=>5555555555,
			'fix_number'=>5555555,
			'date_start'=>'2005/05/25',
			'code_adviser'=>10004,
			'zone'=>"2,3",
			'user_id'=>8
			)
		);
	}
}
